""" Any valuable constants """
ORIENTATION_NORMAL = '1'
ORIENTATION_UPSIDE_DOWN = '3'
ORIENTATION_TOP_TO_LEFT = '6'
ORIENTATION_TOP_TO_RIGHT = '8'

MEDIA_TYPE_IMAGE = 'IMAGE'

CONF_UPDATE_INTERVAL = 'update_interval'
CONF_UPDATE_INTERVAL_ALBUM = 'album'
CONF_UPDATE_INTERVAL_IMAGE = 'image'
CONF_SHARED_ALBUMS = "shared_albums"

UPDATE_INTERVAL_ALBUM = 0
UPDATE_INTERVAL_IMAGE = 1

IMAGE_WIDTH = 0
IMAGE_HEIGHT = 1


